/**************** HCI error codes returned by Event 0F *****************/

char* error0f[70] = {
    "",
    "Unknown HCI Command",
    "Unknown Connection Identifier",
    "Hardware Failure",
    "Page Timeout",
    "Authentication Failure",
    "PIN or Key Missing",
    "Memory Capacity Exceeded",
    "Connection Timeout",
    "Connection Limit Exceeded",
    "Synchronous Connection Limit To A Device Exceeded",
    "Connection Already Exists",
    "Command Disallowed",
    "Connection Rejected due to Limited Resources",
    "Connection Rejected Due To Security Reasons",
    "Connection Rejected due to Unacceptable BD_ADDR",
    "Connection Accept Timeout Exceeded",
    "Unsupported Feature or Parameter Value",
    "Invalid HCI Command Parameters",
    "Remote User Terminated Connection",
    "Remote Device Terminated Connection due to Low Resources",
    "Remote Device Terminated Connection due to Power Off",
    "Connection Terminated By Local Host",
    "Repeated Attempts",
    "Pairing Not Allowed",
    "Unknown LMP PDU",
    "Unsupported Remote/LMP Feature",
    "SCO Offset Rejected",
    "SCO Interval Rejected",
    "SCO Air Mode Rejected",
    "Invalid LMP/LL Parameters",
    "Unspecified Error",
    "Unsupported LMP/LL Parameter Value",
    "Role Change Not Allowed",
    "LMP/LL Response Timeout",
    "LMP/LL Collision",
    "LMP PDU Not Allowed",
    "Encryption Mode Not Acceptable",
    "Link Key cannot be Changed",
    "Requested QoS Not Supported",
    "Instant Passed",
    "Pairing With Unit Key Not Supported",
    "Different Transaction Collision",
    "Reserved for future use",
    "QoS Unacceptable Parameter",
    "QoS Rejected",
    "Channel Classification Not Supported",
    "Insufficient Security",
    "Parameter Out Of Mandatory Range",
    "Reserved for future use",
    "Role Switch Pending",
    "Reserved for future use",
    "Reserved Slot Violation",
    "Role Switch Failed",
    "Extended Inquiry Response Too Large",
    "Secure Simple Pairing Not Supported By Host",
    "Host Busy - Pairing",
    "No Suitable Channel Found",
    "Controller Busy",
    "Unacceptable Connection Parameters",
    "Advertising Timeout",
    "Connection Terminated due to MIC Failure",
    "Connection Failed / Synchronization Timeout",
    "MAC Connection Failed",
    "Coarse Clock Adjustment Rejected",
    "Type0 Submap Not Defined",
    "Unknown Advertising Identifier",
    "Limit Reached",
    "Operation Cancelled by Host",
    "Packet Too Long"
}; // last = [69]